DEFINE
	
/*Run Tests*/
VAR _Tests =               
UNION (
    ROW (
        "TestName", "Measure: Test 1",
        "ExpectedValue", 1,
        "ActualValue", 1
    ),
    ROW (
        "TestName", "Measure: Test 2",
        "ExpectedValue", 1,
        "ActualValue", 1
    ),
	    ROW (
        "TestName", "Measure: Test 3",
        "ExpectedValue", 1,
        "ActualValue", 1
    )
)

/*Output Pass/Fail*/
EVALUATE ADDCOLUMNS(_Tests,"Passed",[ExpectedValue] = [ActualValue])